---
version: '3.8'
services:
  mongo:
    image: mongo:6
    volumes: [mongo_data:/data/db]
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongo:27017/judge
      - JWT_SECRET=changeme
      - PORT=27017
    volumes:
      - ./codespace/server:/app
      - server_node_modules:/app/node_modules
    ports: [27017:27017]
    depends_on: [mongo]
  client:
    build: ./codespace/frontend
    environment: [REACT_APP_SERVER_URL=http://server:27017]
    volumes:
      - ./codespace/frontend:/app
      - client_node_modules:/app/node_modules
    ports: [3000:3000]
    depends_on: [server]
  judge:
    build: ./codespace/Docker
    depends_on: [server]
volumes:
  mongo_data:
  server_node_modules:
  client_node_modules:
